// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package compresspdftest.proxies;

public class CompressionSettings implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject compressionSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CompressPdfTest.CompressionSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CompressionLevel("CompressionLevel"),
		MinFileSize("MinFileSize");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CompressionSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CompressionSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject compressionSettingsMendixObject)
	{
		if (compressionSettingsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, compressionSettingsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.compressionSettingsMendixObject = compressionSettingsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static compresspdftest.proxies.CompressionSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new compresspdftest.proxies.CompressionSettings(context, mendixObject);
	}

	public static compresspdftest.proxies.CompressionSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return compresspdftest.proxies.CompressionSettings.initialize(context, mendixObject);
	}

	/**
	 * @return value of CompressionLevel
	 */
	public final java.lang.Integer getCompressionLevel()
	{
		return getCompressionLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of CompressionLevel
	 */
	public final java.lang.Integer getCompressionLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CompressionLevel.toString());
	}

	/**
	 * Set value of CompressionLevel
	 * @param compressionlevel
	 */
	public final void setCompressionLevel(java.lang.Integer compressionlevel)
	{
		setCompressionLevel(getContext(), compressionlevel);
	}

	/**
	 * Set value of CompressionLevel
	 * @param context
	 * @param compressionlevel
	 */
	public final void setCompressionLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer compressionlevel)
	{
		getMendixObject().setValue(context, MemberNames.CompressionLevel.toString(), compressionlevel);
	}

	/**
	 * @return value of MinFileSize
	 */
	public final java.lang.Integer getMinFileSize()
	{
		return getMinFileSize(getContext());
	}

	/**
	 * @param context
	 * @return value of MinFileSize
	 */
	public final java.lang.Integer getMinFileSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinFileSize.toString());
	}

	/**
	 * Set value of MinFileSize
	 * @param minfilesize
	 */
	public final void setMinFileSize(java.lang.Integer minfilesize)
	{
		setMinFileSize(getContext(), minfilesize);
	}

	/**
	 * Set value of MinFileSize
	 * @param context
	 * @param minfilesize
	 */
	public final void setMinFileSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minfilesize)
	{
		getMendixObject().setValue(context, MemberNames.MinFileSize.toString(), minfilesize);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return compressionSettingsMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final compresspdftest.proxies.CompressionSettings that = (compresspdftest.proxies.CompressionSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
